// hiking-new/src/views/Home.vue
﻿<template>
  <div>
    <Hero />

    <!-- 精选帖子 -->
    <section class="max-w-7xl mx-auto px-6 lg:px-8 py-20">
      <div class="flex items-end justify-between mb-12">
        <div>
          <div class="accent-line mb-4" />
          <h2 class="text-3xl md:text-4xl font-bold text-charcoal">最新精选</h2>
        </div>
        <RouterLink to="/forum" class="group inline-flex items-center gap-2 text-sm font-medium text-forest-700 hover:text-forest-800 transition-colors">
          查看全部
          <svg class="w-4 h-4 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
          </svg>
        </RouterLink>
      </div>

      <!-- 加载中 -->
      <div v-if="loading" class="text-center py-12">
        <div class="inline-block w-8 h-8 border-4 border-forest-500/30 border-t-forest-500 rounded-full animate-spin"></div>
      </div>

      <!-- 帖子列表 -->
      <div v-else class="space-y-6">
        <PostCard v-for="post in posts" :key="post.id" :post="post" />
      </div>

      <!-- 空状态 -->
      <div v-if="!loading && posts.length === 0" class="text-center py-12 bg-white rounded-2xl border border-slate-100">
        <p class="text-slate-500">暂无帖子</p>
      </div>
    </section>

    <!-- 热门路线 -->
    <section class="bg-white py-20">
      <div class="max-w-7xl mx-auto px-6 lg:px-8">
        <div class="flex items-end justify-between mb-12">
          <div>
            <div class="accent-line mb-4" />
            <h2 class="text-3xl md:text-4xl font-bold text-charcoal">热门路线</h2>
          </div>
          <RouterLink to="/routes" class="group inline-flex items-center gap-2 text-sm font-medium text-forest-700 hover:text-forest-800 transition-colors">
            探索更多
            <svg class="w-4 h-4 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
            </svg>
          </RouterLink>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <RouteCard v-for="route in routes" :key="route.id" :route-data="route" />
        </div>
      </div>
    </section>

    <!-- CTA 区域 -->
    <section class="max-w-7xl mx-auto px-6 lg:px-8 py-20">
      <div class="relative rounded-[2rem] overflow-hidden">
        <div class="absolute inset-0">
          <img src="/img/云蒙山.jpg" alt="" class="w-full h-full object-cover" />
          <div class="absolute inset-0 bg-charcoal/60" />
        </div>
        <div class="relative px-8 py-20 md:px-16 md:py-28 text-center">
          <h2 class="text-3xl md:text-5xl font-bold text-white mb-4"
              style="font-family: 'Noto Serif SC', serif;">
            准备好出发了吗？
          </h2>
          <p class="text-white/70 max-w-lg mx-auto mb-8 text-lg">
            加入数万名徒步爱好者，发现属于你的下一段旅程
          </p>
          <div class="flex flex-wrap gap-4 justify-center">
            <RouterLink to="/routes" class="px-8 py-4 bg-white text-charcoal font-semibold rounded-2xl hover:bg-forest-50 transition-all shadow-xl">
              查看路线
            </RouterLink>
            <RouterLink to="/forum" class="px-8 py-4 border border-white/30 text-white font-medium rounded-2xl hover:bg-white/10 transition-all">
              加入社区
            </RouterLink>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { RouterLink } from 'vue-router'
import Hero from '@/components/Hero.vue'
import PostCard from '@/components/PostCard.vue'
import RouteCard from '@/components/RouteCard.vue'

const posts = ref([])
const loading = ref(true)

const API_URL = import.meta.env.VITE_API_URL || 'https://hiking-china-api.onrender.com'

async function loadPosts() {
  try {
    const res = await fetch(`${API_URL}/api/posts?limit=5`)
    const data = await res.json()
    posts.value = (data.posts || []).map(p => {
      const images = typeof p.image_urls === 'string' ? JSON.parse(p.image_urls) : (Array.isArray(p.image_urls) ? p.image_urls : [])
      const tags = typeof p.tags === 'string' ? p.tags.split(',').filter(Boolean) : (Array.isArray(p.tags) ? p.tags : [])
      const date = p.created_at ? p.created_at.split('T')[0] : ''
      return {
        id: p.id,
        title: p.title,
        excerpt: (p.content || '').substring(0, 150) + '...',
        author: p.username || '匿名',
        date,
        category: p.category || '其他',
        image: images[0] || '/img/徒步装备.avif',
        images,
        tags,
        views: p.views || 0,
        comments: 0,
      }
    })
  } catch {
    // API 失败，不显示帖子
  } finally {
    loading.value = false
  }
}

const routes = [
  { id: 1, name: '四姑娘山大峰', region: '四川', difficulty: '中级', description: '入门级雪山攀登，体验征服5025米的成就感', distance: 28, duration: '2天', rating: 4.8, image: '/img/四姑娘山.jpg' },
  { id: 2, name: '虎跳峡高路徒步', region: '云南', difficulty: '中级', description: '世界十大经典徒步路线，金沙江峡谷震撼体验', distance: 25, duration: '2天', rating: 4.9, image: '/img/虎跳峡.jpg' },
  { id: 3, name: '稻城亚丁徒步', region: '四川', difficulty: '中级', description: '最后的香格里拉，三神山神圣之旅', distance: 45, duration: '4天', rating: 4.9, image: '/img/稻城亚丁.jpg' },
  { id: 4, name: '喀纳斯环线', region: '新疆', difficulty: '中级', description: '北疆最美秋色，禾木-白哈巴-喀纳斯', distance: 60, duration: '5天', rating: 4.8, image: '/img/喀纳斯.jpg' },
  { id: 5, name: '雨崩村徒步', region: '云南', difficulty: '初级', description: '梅里雪山脚下的世外桃源，藏族村落体验', distance: 20, duration: '3天', rating: 4.7, image: '/img/雨崩村.webp' },
  { id: 6, name: '黄山徒步', region: '安徽', difficulty: '初级', description: '中国山水之美典范，奇松怪石云海温泉', distance: 15, duration: '2天', rating: 4.6, image: '/img/黄山.jpg' },
]

onMounted(() => loadPosts())
</script>

// hiking-new/frontend/client/src/pages/Home/Home.tsx
import { Link } from 'react-router-dom';
import { motion, useReducedMotion, type Variants } from 'framer-motion';
import { ArrowRight } from 'lucide-react';
import HeroSection from '@client/src/components/HeroSection';
import PostCard from '@client/src/components/PostCard';
import RouteCard from '@client/src/components/RouteCard';
import SectionHeader from '@client/src/components/visual/SectionHeader';
import CtaBackgroundCarousel from '@client/src/pages/Home/CtaBackgroundCarousel';
import TrailTag from '@client/src/components/visual/TrailTag';
import EmptyState from '@client/src/components/visual/EmptyState';
import CountUpNumber from '@client/src/components/visual/CountUpNumber';
import { HOME_ROUTES } from '@client/src/data/hiking-data';
import { listPosts } from '@client/src/data/hiking-store';
import { useAsyncData } from '@client/src/hooks/use-hiking';
import type { Post, RouteItem } from '@client/src/data/hiking-types';
import { withBasePath } from '@client/src/utils/base-path';
import { Image } from '@client/src/components/ui/image';

const EASE_OUT_EXPO: [number, number, number, number] = [0.16, 1, 0.3, 1];

const sectionReveal = {
  initial: { opacity: 0, y: 24 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: '-80px' },
  transition: { duration: 0.9, ease: EASE_OUT_EXPO },
};

const Home = () => {
  const prefersReduced: boolean = useReducedMotion() ?? false;
  const { data: postsData, loading } = useAsyncData<Post[]>(() => listPosts({ limit: 5 }), []);
  const posts: Post[] = loading ? [] : postsData ?? [];
  const routes: RouteItem[] = HOME_ROUTES;
  const featured: RouteItem | undefined = routes[0];
  const restRoutes: RouteItem[] = routes.slice(1);

  const cardItemVariants: Variants = prefersReduced
    ? {}
    : {
        hidden: { opacity: 0, y: 24 },
        visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: EASE_OUT_EXPO } },
      };
  const listVariants: Variants = prefersReduced
    ? {}
    : { visible: { transition: { staggerChildren: 0.09, delayChildren: 0.05 } } };

  return (
    <div>
      <HeroSection />

      {/* 精选帖子 */}
      <motion.section {...sectionReveal} className="max-w-7xl mx-auto px-4 md:px-6 lg:px-8 py-10 md:py-20">
        <SectionHeader
          index="01"
          kicker="Latest"
          title="最新精选"
          className="mb-6 md:mb-12"
          action={
            <Link
              to="/forum"
              className="group inline-flex items-center gap-1.5 text-xs md:text-sm font-medium text-pine-700 hover:text-pine-800 transition-colors"
            >
              查看全部
              <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
            </Link>
          }
        />

        {loading ? (
          <div className="grid grid-cols-2 gap-x-3 gap-y-5 md:block md:space-y-5">
            {[0, 1, 2, 3, 4].map((i: number) => (
              <div key={i} className="animate-pulse rounded-lg bg-muted h-32 md:h-40" />
            ))}
          </div>
        ) : posts.length === 0 ? (
          <EmptyState
            title="暂无帖子"
            description="这里还没有内容。去论坛看看大家都在聊什么，或发布你的第一篇徒步记录。"
            action={
              <Link
                to="/forum"
                className="inline-flex items-center gap-2 rounded-lg bg-pine-700 px-4 py-2 md:px-5 md:py-2.5 text-sm font-medium text-paper hover:bg-pine-800 transition-colors"
              >
                进入论坛
                <ArrowRight size={14} />
              </Link>
            }
          />
        ) : (
          <motion.div
            className="grid grid-cols-2 gap-x-3 gap-y-5 md:block md:space-y-5"
            variants={listVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-60px' }}
          >
            {posts.map((post: Post) => (
              <motion.div key={post.id} variants={cardItemVariants}>
                <PostCard post={post} />
              </motion.div>
            ))}
          </motion.div>
        )}
      </motion.section>

      {/* 热门路线：主从布局 */}
      <motion.section {...sectionReveal} className="max-w-7xl mx-auto px-4 md:px-6 lg:px-8 py-10 md:py-20">
        <SectionHeader
          index="02"
          kicker="Routes"
          title="热门路线"
          className="mb-6 md:mb-12"
          action={
            <Link
              to="/routes"
              className="group inline-flex items-center gap-1.5 text-xs md:text-sm font-medium text-pine-700 hover:text-pine-800 transition-colors"
            >
              探索更多
              <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
            </Link>
          }
        />

        {/* 通栏特色大卡 */}
        {featured && (
          <Link
            to={`/post/${featured.id}`}
            className="group relative block h-[240px] md:h-[420px] overflow-hidden rounded-xl"
          >
            <Image
              src={withBasePath(featured.image)}
              alt={featured.name}
              className="absolute inset-0 h-full w-full object-cover transition-transform duration-[1600ms] ease-out-expo group-hover:scale-[1.06]"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-ink/70 via-ink/25 to-transparent" />
            <div className="absolute inset-x-0 bottom-0 flex items-end justify-between gap-4 p-4 md:gap-6 md:p-8">
              <div className="min-w-0">
                <div className="mb-3 flex flex-wrap gap-2">
                  <TrailTag tone="mist">{featured.difficulty}</TrailTag>
                  <TrailTag tone="mist">{featured.region}</TrailTag>
                </div>
                <h3 className="font-display text-lg md:text-h1 text-paper">{featured.name}</h3>
                <p className="mt-2 md:mt-3 font-data text-xs md:text-sm tracking-wide text-paper/85">
                  <CountUpNumber value={featured.distance} /> KM · {featured.duration} · 评分{' '}
                  <CountUpNumber value={featured.rating} decimals={1} />
                </p>
              </div>
              <span className="hidden shrink-0 items-center gap-1.5 text-sm font-medium text-paper sm:inline-flex">
                查看路线
                <ArrowRight
                  size={16}
                  className="transition-transform ease-out-expo group-hover:translate-x-0.5"
                />
              </span>
            </div>
          </Link>
        )}

        {/* 其余路线（网格恒封面卡，RouteCard 已纯封面化） */}
        {restRoutes.length > 0 && (
          <motion.div
            className="mt-4 md:mt-6 grid grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-x-3 gap-y-5 md:gap-6"
            variants={listVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-60px' }}
          >
            {restRoutes.map((route: RouteItem) => (
              <motion.div key={route.id} variants={cardItemVariants}>
                <RouteCard routeData={route} />
              </motion.div>
            ))}
          </motion.div>
        )}
      </motion.section>

      {/* CTA：深松色带 */}
      <motion.section {...sectionReveal} className="max-w-7xl mx-auto px-4 md:px-6 lg:px-8 py-10 md:py-20">
        <div className="relative overflow-hidden rounded-xl px-5 py-10 md:px-12 md:py-20">
          {/* 真实摄影背景轮播 + 暗色遮罩（向左渐隐） */}
          <CtaBackgroundCarousel />
          <div className="relative max-w-2xl">
            <p className="text-kicker uppercase text-ember-400">Next Trail Awaits</p>
            <h2 className="mt-3 font-display text-xl md:text-h2 text-paper">准备好出发了吗</h2>
            <p className="mt-4 text-xs md:text-base text-pine-300 leading-relaxed">
              加入数万名徒步爱好者，发现属于你的下一段旅程。从路线规划到结伴同行，山野之间自有答案。
            </p>
            <div className="mt-6 md:mt-8 flex flex-wrap gap-3 md:gap-4">
              <Link
                to="/routes"
                className="group relative inline-flex items-center gap-2 rounded-lg bg-ember-500 hover:bg-ember-600 text-paper px-3 py-1.5 text-xs md:px-6 md:py-3 md:text-base font-medium transition-colors after:absolute after:inset-x-4 md:after:inset-x-6 after:bottom-1.5 after:h-px after:origin-left after:scale-x-0 after:bg-paper/70 after:transition-transform after:duration-500 hover:after:scale-x-100"
              >
                查看路线
                <ArrowRight size={16} className="group-hover:translate-x-0.5 transition-transform" />
              </Link>
              <Link
                to="/forum"
                className="inline-flex items-center rounded-lg border border-pine-700 text-pine-100 hover:bg-pine-900 px-3 py-1.5 text-xs md:px-6 md:py-3 md:text-base font-medium transition-colors"
              >
                加入社区
              </Link>
            </div>
          </div>
        </div>
      </motion.section>
    </div>
  );
};

export default Home;
